### ISSUE TITLE
Prisma2 generate & dev  print a huge amount of data

### ISSUE THREAD

**Issue by Gbahaa** [prisma/prisma2-cli#14]
In the latest 0.0.97 version, `prisma2 generate` outputs a huge amount of data. 

Here is just a snapshot
![Screenshot from 2019-06-27 16-34-01](https://user-images.githubusercontent.com/24666329/60246532-d1769900-98f9-11e9-8979-b63cb29f8003.png)

Prisma2 0.0.97
MySql 5.7
Ubuntu 16.04

**Comment by timsuchanek** [comment]
Thanks for reporting @Gbahaa! How does your data model look like?

**Comment by Gbahaa** [comment]
It was not related to the data model (big or small)  as I tried two different data models (one of them is in the graphql example)

**Comment by timsuchanek** [comment]
Thanks, I also could reproduce this on an arbitrary data model.
We just published a fix in `prisma2@0.0.99`
